// Plugin-specific config protos for InputVariableSetter plugins.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: api/adaptive_load/input_variable_setter_impl.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Configuration for RequestsPerSecondInputVariableSetter (plugin name: "nighthawk.rps")
// that sets |requests_per_second| within CommandLineOptions to a numeric value
// being varied by a StepController.
type RequestsPerSecondInputVariableSetterConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RequestsPerSecondInputVariableSetterConfig) Reset() {
	*x = RequestsPerSecondInputVariableSetterConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_adaptive_load_input_variable_setter_impl_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestsPerSecondInputVariableSetterConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestsPerSecondInputVariableSetterConfig) ProtoMessage() {}

func (x *RequestsPerSecondInputVariableSetterConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_adaptive_load_input_variable_setter_impl_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestsPerSecondInputVariableSetterConfig.ProtoReflect.Descriptor instead.
func (*RequestsPerSecondInputVariableSetterConfig) Descriptor() ([]byte, []int) {
	return file_api_adaptive_load_input_variable_setter_impl_proto_rawDescGZIP(), []int{0}
}

var File_api_adaptive_load_input_variable_setter_impl_proto protoreflect.FileDescriptor

var file_api_adaptive_load_input_variable_setter_impl_proto_rawDesc = []byte{
	0x0a, 0x32, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x64, 0x61, 0x70, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x6c,
	0x6f, 0x61, 0x64, 0x2f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x5f, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62,
	0x6c, 0x65, 0x5f, 0x73, 0x65, 0x74, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x6d, 0x70, 0x6c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x6e, 0x69, 0x67, 0x68, 0x74, 0x68, 0x61, 0x77, 0x6b, 0x2e,
	0x61, 0x64, 0x61, 0x70, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x2c, 0x0a,
	0x2a, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x50, 0x65, 0x72, 0x53, 0x65, 0x63, 0x6f,
	0x6e, 0x64, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x53,
	0x65, 0x74, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x42, 0x04, 0x5a, 0x02, 0x2e,
	0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_adaptive_load_input_variable_setter_impl_proto_rawDescOnce sync.Once
	file_api_adaptive_load_input_variable_setter_impl_proto_rawDescData = file_api_adaptive_load_input_variable_setter_impl_proto_rawDesc
)

func file_api_adaptive_load_input_variable_setter_impl_proto_rawDescGZIP() []byte {
	file_api_adaptive_load_input_variable_setter_impl_proto_rawDescOnce.Do(func() {
		file_api_adaptive_load_input_variable_setter_impl_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_adaptive_load_input_variable_setter_impl_proto_rawDescData)
	})
	return file_api_adaptive_load_input_variable_setter_impl_proto_rawDescData
}

var file_api_adaptive_load_input_variable_setter_impl_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_adaptive_load_input_variable_setter_impl_proto_goTypes = []interface{}{
	(*RequestsPerSecondInputVariableSetterConfig)(nil), // 0: nighthawk.adaptive_load.RequestsPerSecondInputVariableSetterConfig
}
var file_api_adaptive_load_input_variable_setter_impl_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_adaptive_load_input_variable_setter_impl_proto_init() }
func file_api_adaptive_load_input_variable_setter_impl_proto_init() {
	if File_api_adaptive_load_input_variable_setter_impl_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_adaptive_load_input_variable_setter_impl_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestsPerSecondInputVariableSetterConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_adaptive_load_input_variable_setter_impl_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_adaptive_load_input_variable_setter_impl_proto_goTypes,
		DependencyIndexes: file_api_adaptive_load_input_variable_setter_impl_proto_depIdxs,
		MessageInfos:      file_api_adaptive_load_input_variable_setter_impl_proto_msgTypes,
	}.Build()
	File_api_adaptive_load_input_variable_setter_impl_proto = out.File
	file_api_adaptive_load_input_variable_setter_impl_proto_rawDesc = nil
	file_api_adaptive_load_input_variable_setter_impl_proto_goTypes = nil
	file_api_adaptive_load_input_variable_setter_impl_proto_depIdxs = nil
}
