// Plugin-specific config protos for ScoringFunction plugins.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: api/adaptive_load/scoring_function_impl.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Configuration for BinaryScoringFunction (plugin name: "nighthawk.binary_scoring") that
// is 1.0 when the value is within thresholds and -1.0 otherwise.
type BinaryScoringFunctionConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The minimum allowed value of the metric. Optional, default -infinity.
	LowerThreshold *wrapperspb.DoubleValue `protobuf:"bytes,1,opt,name=lower_threshold,json=lowerThreshold,proto3" json:"lower_threshold,omitempty"`
	// The maximum allowed value of the metric. Optional, default infinity.
	UpperThreshold *wrapperspb.DoubleValue `protobuf:"bytes,2,opt,name=upper_threshold,json=upperThreshold,proto3" json:"upper_threshold,omitempty"`
}

func (x *BinaryScoringFunctionConfig) Reset() {
	*x = BinaryScoringFunctionConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_adaptive_load_scoring_function_impl_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BinaryScoringFunctionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryScoringFunctionConfig) ProtoMessage() {}

func (x *BinaryScoringFunctionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_adaptive_load_scoring_function_impl_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinaryScoringFunctionConfig.ProtoReflect.Descriptor instead.
func (*BinaryScoringFunctionConfig) Descriptor() ([]byte, []int) {
	return file_api_adaptive_load_scoring_function_impl_proto_rawDescGZIP(), []int{0}
}

func (x *BinaryScoringFunctionConfig) GetLowerThreshold() *wrapperspb.DoubleValue {
	if x != nil {
		return x.LowerThreshold
	}
	return nil
}

func (x *BinaryScoringFunctionConfig) GetUpperThreshold() *wrapperspb.DoubleValue {
	if x != nil {
		return x.UpperThreshold
	}
	return nil
}

// Configuration for LinearScoringFunction (plugin name: "nighthawk.linear_scoring") that
// calculates a metric score as k * (threshold - value), where k is a scaling constant. The score is
// 0.0 when the value exactly equals the threshold, positive below the threshold (meaning input
// should ramp up), and negative above the threshold. The score is proportional to the difference
// from the threshold.
type LinearScoringFunctionConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The target value of the metric. Required.
	Threshold float64 `protobuf:"fixed64,1,opt,name=threshold,proto3" json:"threshold,omitempty"`
	// Scaling constant: score = scaling_constant * (threshold - value). Use this in combination
	// with step controller constants to produce reasonable input increments for reasonable
	// differences from the threshold. Required.
	ScalingConstant float64 `protobuf:"fixed64,2,opt,name=scaling_constant,json=scalingConstant,proto3" json:"scaling_constant,omitempty"`
}

func (x *LinearScoringFunctionConfig) Reset() {
	*x = LinearScoringFunctionConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_adaptive_load_scoring_function_impl_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinearScoringFunctionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinearScoringFunctionConfig) ProtoMessage() {}

func (x *LinearScoringFunctionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_adaptive_load_scoring_function_impl_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinearScoringFunctionConfig.ProtoReflect.Descriptor instead.
func (*LinearScoringFunctionConfig) Descriptor() ([]byte, []int) {
	return file_api_adaptive_load_scoring_function_impl_proto_rawDescGZIP(), []int{1}
}

func (x *LinearScoringFunctionConfig) GetThreshold() float64 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *LinearScoringFunctionConfig) GetScalingConstant() float64 {
	if x != nil {
		return x.ScalingConstant
	}
	return 0
}

var File_api_adaptive_load_scoring_function_impl_proto protoreflect.FileDescriptor

var file_api_adaptive_load_scoring_function_impl_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x64, 0x61, 0x70, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x6c,
	0x6f, 0x61, 0x64, 0x2f, 0x73, 0x63, 0x6f, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x66, 0x75, 0x6e, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6d, 0x70, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x17, 0x6e, 0x69, 0x67, 0x68, 0x74, 0x68, 0x61, 0x77, 0x6b, 0x2e, 0x61, 0x64, 0x61, 0x70, 0x74,
	0x69, 0x76, 0x65, 0x5f, 0x6c, 0x6f, 0x61, 0x64, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65,
	0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xab, 0x01, 0x0a, 0x1b, 0x42, 0x69, 0x6e,
	0x61, 0x72, 0x79, 0x53, 0x63, 0x6f, 0x72, 0x69, 0x6e, 0x67, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x45, 0x0a, 0x0f, 0x6c, 0x6f, 0x77, 0x65,
	0x72, 0x5f, 0x74, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52,
	0x0e, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x54, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x12,
	0x45, 0x0a, 0x0f, 0x75, 0x70, 0x70, 0x65, 0x72, 0x5f, 0x74, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f,
	0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x6f, 0x75, 0x62, 0x6c,
	0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x0e, 0x75, 0x70, 0x70, 0x65, 0x72, 0x54, 0x68, 0x72,
	0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x22, 0x66, 0x0a, 0x1b, 0x4c, 0x69, 0x6e, 0x65, 0x61, 0x72,
	0x53, 0x63, 0x6f, 0x72, 0x69, 0x6e, 0x67, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f,
	0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x74, 0x68, 0x72, 0x65, 0x73, 0x68,
	0x6f, 0x6c, 0x64, 0x12, 0x29, 0x0a, 0x10, 0x73, 0x63, 0x61, 0x6c, 0x69, 0x6e, 0x67, 0x5f, 0x63,
	0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0f, 0x73,
	0x63, 0x61, 0x6c, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x42, 0x04,
	0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_adaptive_load_scoring_function_impl_proto_rawDescOnce sync.Once
	file_api_adaptive_load_scoring_function_impl_proto_rawDescData = file_api_adaptive_load_scoring_function_impl_proto_rawDesc
)

func file_api_adaptive_load_scoring_function_impl_proto_rawDescGZIP() []byte {
	file_api_adaptive_load_scoring_function_impl_proto_rawDescOnce.Do(func() {
		file_api_adaptive_load_scoring_function_impl_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_adaptive_load_scoring_function_impl_proto_rawDescData)
	})
	return file_api_adaptive_load_scoring_function_impl_proto_rawDescData
}

var file_api_adaptive_load_scoring_function_impl_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_adaptive_load_scoring_function_impl_proto_goTypes = []interface{}{
	(*BinaryScoringFunctionConfig)(nil), // 0: nighthawk.adaptive_load.BinaryScoringFunctionConfig
	(*LinearScoringFunctionConfig)(nil), // 1: nighthawk.adaptive_load.LinearScoringFunctionConfig
	(*wrapperspb.DoubleValue)(nil),      // 2: google.protobuf.DoubleValue
}
var file_api_adaptive_load_scoring_function_impl_proto_depIdxs = []int32{
	2, // 0: nighthawk.adaptive_load.BinaryScoringFunctionConfig.lower_threshold:type_name -> google.protobuf.DoubleValue
	2, // 1: nighthawk.adaptive_load.BinaryScoringFunctionConfig.upper_threshold:type_name -> google.protobuf.DoubleValue
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_adaptive_load_scoring_function_impl_proto_init() }
func file_api_adaptive_load_scoring_function_impl_proto_init() {
	if File_api_adaptive_load_scoring_function_impl_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_adaptive_load_scoring_function_impl_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BinaryScoringFunctionConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_adaptive_load_scoring_function_impl_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LinearScoringFunctionConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_adaptive_load_scoring_function_impl_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_adaptive_load_scoring_function_impl_proto_goTypes,
		DependencyIndexes: file_api_adaptive_load_scoring_function_impl_proto_depIdxs,
		MessageInfos:      file_api_adaptive_load_scoring_function_impl_proto_msgTypes,
	}.Build()
	File_api_adaptive_load_scoring_function_impl_proto = out.File
	file_api_adaptive_load_scoring_function_impl_proto_rawDesc = nil
	file_api_adaptive_load_scoring_function_impl_proto_goTypes = nil
	file_api_adaptive_load_scoring_function_impl_proto_depIdxs = nil
}
