// Plugin-specific config protos for StepController plugins.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: api/adaptive_load/step_controller_impl.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	v3 "github.com/envoyproxy/go-control-plane/envoy/config/core/v3"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Configuration for ExponentialSearchStepController (plugin name:
// "nighthawk.exponential_search") that performs an exponential search for the optimal
// value of a single Nighthawk input variable (e.g. RPS). Exponential search
// starts with the input set to |initial_value| and increases the input by
// |exponential_factor| until the metric goes outside thresholds at some input
// value X (i.e. the sign of the score becomes negative); then it performs a
// binary search with input values between (X/exponential_factor) and X for the
// highest input value for which the metric is within thresholds.
type ExponentialSearchStepControllerConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Selects a plugin that knows how to apply a numeric value generated by the
	// StepController within CommandLineOptions. Optional, defaults to "nighthawk.rps"
	// plugin, which sets |requests_per_second| in CommandLineOptions.
	InputVariableSetter *v3.TypedExtensionConfig `protobuf:"bytes,1,opt,name=input_variable_setter,json=inputVariableSetter,proto3" json:"input_variable_setter,omitempty"`
	// Initial value of the input variable that should be attempted. Required.
	InitialValue float64 `protobuf:"fixed64,2,opt,name=initial_value,json=initialValue,proto3" json:"initial_value,omitempty"`
	// Factor to increase the input variable during the exponential phase.
	// Optional, default 2.0.
	ExponentialFactor float64 `protobuf:"fixed64,3,opt,name=exponential_factor,json=exponentialFactor,proto3" json:"exponential_factor,omitempty"`
}

func (x *ExponentialSearchStepControllerConfig) Reset() {
	*x = ExponentialSearchStepControllerConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_adaptive_load_step_controller_impl_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExponentialSearchStepControllerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExponentialSearchStepControllerConfig) ProtoMessage() {}

func (x *ExponentialSearchStepControllerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_adaptive_load_step_controller_impl_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExponentialSearchStepControllerConfig.ProtoReflect.Descriptor instead.
func (*ExponentialSearchStepControllerConfig) Descriptor() ([]byte, []int) {
	return file_api_adaptive_load_step_controller_impl_proto_rawDescGZIP(), []int{0}
}

func (x *ExponentialSearchStepControllerConfig) GetInputVariableSetter() *v3.TypedExtensionConfig {
	if x != nil {
		return x.InputVariableSetter
	}
	return nil
}

func (x *ExponentialSearchStepControllerConfig) GetInitialValue() float64 {
	if x != nil {
		return x.InitialValue
	}
	return 0
}

func (x *ExponentialSearchStepControllerConfig) GetExponentialFactor() float64 {
	if x != nil {
		return x.ExponentialFactor
	}
	return 0
}

var File_api_adaptive_load_step_controller_impl_proto protoreflect.FileDescriptor

var file_api_adaptive_load_step_controller_impl_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x64, 0x61, 0x70, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x6c,
	0x6f, 0x61, 0x64, 0x2f, 0x73, 0x74, 0x65, 0x70, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x6c, 0x65, 0x72, 0x5f, 0x69, 0x6d, 0x70, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17,
	0x6e, 0x69, 0x67, 0x68, 0x74, 0x68, 0x61, 0x77, 0x6b, 0x2e, 0x61, 0x64, 0x61, 0x70, 0x74, 0x69,
	0x76, 0x65, 0x5f, 0x6c, 0x6f, 0x61, 0x64, 0x1a, 0x24, 0x65, 0x6e, 0x76, 0x6f, 0x79, 0x2f, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x76, 0x33, 0x2f, 0x65, 0x78,
	0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xdb, 0x01,
	0x0a, 0x25, 0x45, 0x78, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x53, 0x74, 0x65, 0x70, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65,
	0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x5e, 0x0a, 0x15, 0x69, 0x6e, 0x70, 0x75, 0x74,
	0x5f, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x74, 0x74, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x65, 0x6e, 0x76, 0x6f, 0x79, 0x2e, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x76, 0x33, 0x2e, 0x54, 0x79,
	0x70, 0x65, 0x64, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x52, 0x13, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c,
	0x65, 0x53, 0x65, 0x74, 0x74, 0x65, 0x72, 0x12, 0x23, 0x0a, 0x0d, 0x69, 0x6e, 0x69, 0x74, 0x69,
	0x61, 0x6c, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0c,
	0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x2d, 0x0a, 0x12,
	0x65, 0x78, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x5f, 0x66, 0x61, 0x63, 0x74,
	0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x11, 0x65, 0x78, 0x70, 0x6f, 0x6e, 0x65,
	0x6e, 0x74, 0x69, 0x61, 0x6c, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x42, 0x04, 0x5a, 0x02, 0x2e,
	0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_adaptive_load_step_controller_impl_proto_rawDescOnce sync.Once
	file_api_adaptive_load_step_controller_impl_proto_rawDescData = file_api_adaptive_load_step_controller_impl_proto_rawDesc
)

func file_api_adaptive_load_step_controller_impl_proto_rawDescGZIP() []byte {
	file_api_adaptive_load_step_controller_impl_proto_rawDescOnce.Do(func() {
		file_api_adaptive_load_step_controller_impl_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_adaptive_load_step_controller_impl_proto_rawDescData)
	})
	return file_api_adaptive_load_step_controller_impl_proto_rawDescData
}

var file_api_adaptive_load_step_controller_impl_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_adaptive_load_step_controller_impl_proto_goTypes = []interface{}{
	(*ExponentialSearchStepControllerConfig)(nil), // 0: nighthawk.adaptive_load.ExponentialSearchStepControllerConfig
	(*v3.TypedExtensionConfig)(nil),                  // 1: envoy.config.core.v3.TypedExtensionConfig
}
var file_api_adaptive_load_step_controller_impl_proto_depIdxs = []int32{
	1, // 0: nighthawk.adaptive_load.ExponentialSearchStepControllerConfig.input_variable_setter:type_name -> envoy.config.core.v3.TypedExtensionConfig
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_adaptive_load_step_controller_impl_proto_init() }
func file_api_adaptive_load_step_controller_impl_proto_init() {
	if File_api_adaptive_load_step_controller_impl_proto != nil {
		return
	}
	// TODO:
	//file_envoy_config_core_v3_extension_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_adaptive_load_step_controller_impl_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExponentialSearchStepControllerConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_adaptive_load_step_controller_impl_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_adaptive_load_step_controller_impl_proto_goTypes,
		DependencyIndexes: file_api_adaptive_load_step_controller_impl_proto_depIdxs,
		MessageInfos:      file_api_adaptive_load_step_controller_impl_proto_msgTypes,
	}.Build()
	File_api_adaptive_load_step_controller_impl_proto = out.File
	file_api_adaptive_load_step_controller_impl_proto_rawDesc = nil
	file_api_adaptive_load_step_controller_impl_proto_goTypes = nil
	file_api_adaptive_load_step_controller_impl_proto_depIdxs = nil
}
